// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

#[allow(unsafe_code)]

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -983047788;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__attach_event_subscription_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "attach_event_subscription",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_attach_epoch = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::BridgeTransportError>((move || {
                    let output_ok = crate::attach_event_subscription(api_attach_epoch)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__close_event_connection_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_event_connection",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::close_event_connection()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__exit_failed_runtime_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "exit_failed_runtime",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::exit_failed_runtime(api_expected_runtime_instance_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__export_startup_diagnostics_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_startup_diagnostics",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            let api_request = <crate::DiagnosticsExportRequestDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::export_startup_diagnostics(
                        api_expected_runtime_instance_id,
                        api_request,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__general_shutdown_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "general_shutdown",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::general_shutdown()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__get_appearance_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_appearance_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::get_appearance_settings()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__get_event_attach_epoch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_event_attach_epoch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::get_event_attach_epoch()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__get_runtime_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_runtime_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::get_runtime_state()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__initialize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::initialize()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__initialize_with_data_directory_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_with_data_directory",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data_directory = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::initialize_with_data_directory(api_data_directory)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__open_startup_data_directory_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_startup_data_directory",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok =
                        crate::open_startup_data_directory(api_expected_runtime_instance_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__reset_appearance_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reset_appearance_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok =
                        crate::reset_appearance_settings(api_expected_runtime_instance_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__retry_startup_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "retry_startup",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::retry_startup(api_expected_runtime_instance_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__startup_technical_details_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "startup_technical_details",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_expected_runtime_instance_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok =
                        crate::startup_technical_details(api_expected_runtime_instance_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__subscribe_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "subscribe_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_attach_epoch = <u64>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::RuntimeEventDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::BridgeTransportError>((move || {
                    let output_ok = crate::subscribe_events(api_attach_epoch, api_sink)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__update_appearance_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_appearance_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::UpdateAppearanceSettingsRequestDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::ApplicationErrorDto>((move || {
                    let output_ok = crate::update_appearance_settings(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::RuntimeEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::AppearanceSettingsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_themeMode = <crate::ThemeModeDto>::sse_decode(deserializer);
        return crate::AppearanceSettingsDto {
            theme_mode: var_themeMode,
        };
    }
}

impl SseDecode for crate::ApplicationErrorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_category = <String>::sse_decode(deserializer);
        let mut var_severity = <String>::sse_decode(deserializer);
        let mut var_recoverability = <String>::sse_decode(deserializer);
        let mut var_retryPolicy = <String>::sse_decode(deserializer);
        let mut var_messageKey = <String>::sse_decode(deserializer);
        let mut var_traceId = <String>::sse_decode(deserializer);
        let mut var_safeContext = <Vec<crate::SafeContextEntryDto>>::sse_decode(deserializer);
        return crate::ApplicationErrorDto {
            code: var_code,
            category: var_category,
            severity: var_severity,
            recoverability: var_recoverability,
            retry_policy: var_retryPolicy,
            message_key: var_messageKey,
            trace_id: var_traceId,
            safe_context: var_safeContext,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::BridgeTransportError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::BridgeTransportError::EventStreamClosed,
            _ => unreachable!("Invalid variant for BridgeTransportError: {}", inner),
        };
    }
}

impl SseDecode for crate::DiagnosticsExportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <crate::DiagnosticsExportOutcomeDto>::sse_decode(deserializer);
        let mut var_destinationClassification = <String>::sse_decode(deserializer);
        return crate::DiagnosticsExportDto {
            outcome: var_outcome,
            destination_classification: var_destinationClassification,
        };
    }
}

impl SseDecode for crate::DiagnosticsExportOutcomeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::DiagnosticsExportOutcomeDto::Created,
            1 => crate::DiagnosticsExportOutcomeDto::Partial,
            _ => unreachable!("Invalid variant for DiagnosticsExportOutcomeDto: {}", inner),
        };
    }
}

impl SseDecode for crate::DiagnosticsExportRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_destination = <String>::sse_decode(deserializer);
        return crate::DiagnosticsExportRequestDto {
            destination: var_destination,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::RecoveryActionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::RecoveryActionDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::SafeContextEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::SafeContextEntryDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::StartupFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::StartupFailureDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::StartupPhaseDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::StartupPhaseDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::RecoveryActionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::RecoveryActionKindDto>::sse_decode(deserializer);
        return crate::RecoveryActionDto { kind: var_kind };
    }
}

impl SseDecode for crate::RecoveryActionKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::RecoveryActionKindDto::RetryStartup,
            1 => crate::RecoveryActionKindDto::ResetAppearanceSettings,
            2 => crate::RecoveryActionKindDto::ExportDiagnostics,
            3 => crate::RecoveryActionKindDto::CopyTechnicalDetails,
            4 => crate::RecoveryActionKindDto::OpenDataDirectory,
            5 => crate::RecoveryActionKindDto::Exit,
            _ => unreachable!("Invalid variant for RecoveryActionKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::RuntimeEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_runtimeInstanceId = <String>::sse_decode(deserializer);
        let mut var_sequence = <u64>::sse_decode(deserializer);
        let mut var_occurredAtMs = <u64>::sse_decode(deserializer);
        let mut var_payload = <crate::RuntimeEventPayloadDto>::sse_decode(deserializer);
        return crate::RuntimeEventDto {
            runtime_instance_id: var_runtimeInstanceId,
            sequence: var_sequence,
            occurred_at_ms: var_occurredAtMs,
            payload: var_payload,
        };
    }
}

impl SseDecode for crate::RuntimeEventPayloadDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_lifecycle = <crate::RuntimeLifecycleDto>::sse_decode(deserializer);
                return crate::RuntimeEventPayloadDto::RuntimeStateChanged {
                    lifecycle: var_lifecycle,
                };
            }
            1 => {
                let mut var_phase = <crate::StartupPhaseDto>::sse_decode(deserializer);
                return crate::RuntimeEventPayloadDto::StartupFailed { phase: var_phase };
            }
            2 => {
                return crate::RuntimeEventPayloadDto::AppearanceSettingsChanged;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::RuntimeLifecycleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::RuntimeLifecycleDto::Uninitialized,
            1 => crate::RuntimeLifecycleDto::Starting,
            2 => crate::RuntimeLifecycleDto::Ready,
            3 => crate::RuntimeLifecycleDto::StartupFailed,
            4 => crate::RuntimeLifecycleDto::ShuttingDown,
            5 => crate::RuntimeLifecycleDto::Stopped,
            _ => unreachable!("Invalid variant for RuntimeLifecycleDto: {}", inner),
        };
    }
}

impl SseDecode for crate::RuntimeStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_runtimeInstanceId = <String>::sse_decode(deserializer);
        let mut var_lifecycleState = <crate::RuntimeLifecycleDto>::sse_decode(deserializer);
        let mut var_startupPhase = <Option<crate::StartupPhaseDto>>::sse_decode(deserializer);
        let mut var_startupFailure = <Option<crate::StartupFailureDto>>::sse_decode(deserializer);
        return crate::RuntimeStateDto {
            runtime_instance_id: var_runtimeInstanceId,
            lifecycle_state: var_lifecycleState,
            startup_phase: var_startupPhase,
            startup_failure: var_startupFailure,
        };
    }
}

impl SseDecode for crate::SafeContextEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::SafeContextEntryDto {
            field: var_field,
            value: var_value,
        };
    }
}

impl SseDecode for crate::StartupFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_phase = <crate::StartupPhaseDto>::sse_decode(deserializer);
        let mut var_error = <crate::ApplicationErrorDto>::sse_decode(deserializer);
        let mut var_recoveryActions = <Vec<crate::RecoveryActionDto>>::sse_decode(deserializer);
        return crate::StartupFailureDto {
            phase: var_phase,
            error: var_error,
            recovery_actions: var_recoveryActions,
        };
    }
}

impl SseDecode for crate::StartupPhaseDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::StartupPhaseDto::EnvironmentInitialization,
            1 => crate::StartupPhaseDto::ObservabilityInitialization,
            2 => crate::StartupPhaseDto::ConfigurationInitialization,
            3 => crate::StartupPhaseDto::PersistenceInitialization,
            4 => crate::StartupPhaseDto::SettingsInitialization,
            5 => crate::StartupPhaseDto::CoreServicesInitialization,
            6 => crate::StartupPhaseDto::EventInfrastructureInitialization,
            7 => crate::StartupPhaseDto::ReadinessValidation,
            _ => unreachable!("Invalid variant for StartupPhaseDto: {}", inner),
        };
    }
}

impl SseDecode for crate::TechnicalDetailsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_text = <String>::sse_decode(deserializer);
        return crate::TechnicalDetailsDto { text: var_text };
    }
}

impl SseDecode for crate::ThemeModeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::ThemeModeDto::System,
            1 => crate::ThemeModeDto::Light,
            2 => crate::ThemeModeDto::Dark,
            _ => unreachable!("Invalid variant for ThemeModeDto: {}", inner),
        };
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::UpdateAppearanceSettingsRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_themeMode = <crate::ThemeModeDto>::sse_decode(deserializer);
        return crate::UpdateAppearanceSettingsRequestDto {
            theme_mode: var_themeMode,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__attach_event_subscription_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__close_event_connection_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__exit_failed_runtime_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__export_startup_diagnostics_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__general_shutdown_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__get_appearance_settings_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__get_event_attach_epoch_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__get_runtime_state_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__initialize_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__initialize_with_data_directory_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__open_startup_data_directory_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__reset_appearance_settings_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__retry_startup_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__startup_technical_details_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__subscribe_events_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__update_appearance_settings_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::AppearanceSettingsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.theme_mode.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::AppearanceSettingsDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::AppearanceSettingsDto>
    for crate::AppearanceSettingsDto
{
    fn into_into_dart(self) -> crate::AppearanceSettingsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApplicationErrorDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.category.into_into_dart().into_dart(),
            self.severity.into_into_dart().into_dart(),
            self.recoverability.into_into_dart().into_dart(),
            self.retry_policy.into_into_dart().into_dart(),
            self.message_key.into_into_dart().into_dart(),
            self.trace_id.into_into_dart().into_dart(),
            self.safe_context.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApplicationErrorDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApplicationErrorDto> for crate::ApplicationErrorDto {
    fn into_into_dart(self) -> crate::ApplicationErrorDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::BridgeTransportError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::EventStreamClosed => 0.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::BridgeTransportError {}
impl flutter_rust_bridge::IntoIntoDart<crate::BridgeTransportError>
    for crate::BridgeTransportError
{
    fn into_into_dart(self) -> crate::BridgeTransportError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::DiagnosticsExportDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.destination_classification.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::DiagnosticsExportDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::DiagnosticsExportDto>
    for crate::DiagnosticsExportDto
{
    fn into_into_dart(self) -> crate::DiagnosticsExportDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::DiagnosticsExportOutcomeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Created => 0.into_dart(),
            Self::Partial => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::DiagnosticsExportOutcomeDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::DiagnosticsExportOutcomeDto>
    for crate::DiagnosticsExportOutcomeDto
{
    fn into_into_dart(self) -> crate::DiagnosticsExportOutcomeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::DiagnosticsExportRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.destination.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::DiagnosticsExportRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::DiagnosticsExportRequestDto>
    for crate::DiagnosticsExportRequestDto
{
    fn into_into_dart(self) -> crate::DiagnosticsExportRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RecoveryActionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.kind.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RecoveryActionDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RecoveryActionDto> for crate::RecoveryActionDto {
    fn into_into_dart(self) -> crate::RecoveryActionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RecoveryActionKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::RetryStartup => 0.into_dart(),
            Self::ResetAppearanceSettings => 1.into_dart(),
            Self::ExportDiagnostics => 2.into_dart(),
            Self::CopyTechnicalDetails => 3.into_dart(),
            Self::OpenDataDirectory => 4.into_dart(),
            Self::Exit => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RecoveryActionKindDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RecoveryActionKindDto>
    for crate::RecoveryActionKindDto
{
    fn into_into_dart(self) -> crate::RecoveryActionKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RuntimeEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.runtime_instance_id.into_into_dart().into_dart(),
            self.sequence.into_into_dart().into_dart(),
            self.occurred_at_ms.into_into_dart().into_dart(),
            self.payload.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RuntimeEventDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RuntimeEventDto> for crate::RuntimeEventDto {
    fn into_into_dart(self) -> crate::RuntimeEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RuntimeEventPayloadDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::RuntimeEventPayloadDto::RuntimeStateChanged { lifecycle } => {
                [0.into_dart(), lifecycle.into_into_dart().into_dart()].into_dart()
            }
            crate::RuntimeEventPayloadDto::StartupFailed { phase } => {
                [1.into_dart(), phase.into_into_dart().into_dart()].into_dart()
            }
            crate::RuntimeEventPayloadDto::AppearanceSettingsChanged => [2.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RuntimeEventPayloadDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RuntimeEventPayloadDto>
    for crate::RuntimeEventPayloadDto
{
    fn into_into_dart(self) -> crate::RuntimeEventPayloadDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RuntimeLifecycleDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Uninitialized => 0.into_dart(),
            Self::Starting => 1.into_dart(),
            Self::Ready => 2.into_dart(),
            Self::StartupFailed => 3.into_dart(),
            Self::ShuttingDown => 4.into_dart(),
            Self::Stopped => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RuntimeLifecycleDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RuntimeLifecycleDto> for crate::RuntimeLifecycleDto {
    fn into_into_dart(self) -> crate::RuntimeLifecycleDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::RuntimeStateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.runtime_instance_id.into_into_dart().into_dart(),
            self.lifecycle_state.into_into_dart().into_dart(),
            self.startup_phase.into_into_dart().into_dart(),
            self.startup_failure.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::RuntimeStateDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::RuntimeStateDto> for crate::RuntimeStateDto {
    fn into_into_dart(self) -> crate::RuntimeStateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::SafeContextEntryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.field.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::SafeContextEntryDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::SafeContextEntryDto> for crate::SafeContextEntryDto {
    fn into_into_dart(self) -> crate::SafeContextEntryDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::StartupFailureDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.phase.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
            self.recovery_actions.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::StartupFailureDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::StartupFailureDto> for crate::StartupFailureDto {
    fn into_into_dart(self) -> crate::StartupFailureDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::StartupPhaseDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::EnvironmentInitialization => 0.into_dart(),
            Self::ObservabilityInitialization => 1.into_dart(),
            Self::ConfigurationInitialization => 2.into_dart(),
            Self::PersistenceInitialization => 3.into_dart(),
            Self::SettingsInitialization => 4.into_dart(),
            Self::CoreServicesInitialization => 5.into_dart(),
            Self::EventInfrastructureInitialization => 6.into_dart(),
            Self::ReadinessValidation => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::StartupPhaseDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::StartupPhaseDto> for crate::StartupPhaseDto {
    fn into_into_dart(self) -> crate::StartupPhaseDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::TechnicalDetailsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.text.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::TechnicalDetailsDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::TechnicalDetailsDto> for crate::TechnicalDetailsDto {
    fn into_into_dart(self) -> crate::TechnicalDetailsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ThemeModeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::System => 0.into_dart(),
            Self::Light => 1.into_dart(),
            Self::Dark => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ThemeModeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::ThemeModeDto> for crate::ThemeModeDto {
    fn into_into_dart(self) -> crate::ThemeModeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::UpdateAppearanceSettingsRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.theme_mode.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::UpdateAppearanceSettingsRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::UpdateAppearanceSettingsRequestDto>
    for crate::UpdateAppearanceSettingsRequestDto
{
    fn into_into_dart(self) -> crate::UpdateAppearanceSettingsRequestDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::RuntimeEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::AppearanceSettingsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::ThemeModeDto>::sse_encode(self.theme_mode, serializer);
    }
}

impl SseEncode for crate::ApplicationErrorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.category, serializer);
        <String>::sse_encode(self.severity, serializer);
        <String>::sse_encode(self.recoverability, serializer);
        <String>::sse_encode(self.retry_policy, serializer);
        <String>::sse_encode(self.message_key, serializer);
        <String>::sse_encode(self.trace_id, serializer);
        <Vec<crate::SafeContextEntryDto>>::sse_encode(self.safe_context, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::BridgeTransportError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::BridgeTransportError::EventStreamClosed => 0,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::DiagnosticsExportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::DiagnosticsExportOutcomeDto>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.destination_classification, serializer);
    }
}

impl SseEncode for crate::DiagnosticsExportOutcomeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::DiagnosticsExportOutcomeDto::Created => 0,
                crate::DiagnosticsExportOutcomeDto::Partial => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::DiagnosticsExportRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.destination, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::RecoveryActionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::RecoveryActionDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::SafeContextEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::SafeContextEntryDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::StartupFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::StartupFailureDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::StartupPhaseDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::StartupPhaseDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::RecoveryActionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::RecoveryActionKindDto>::sse_encode(self.kind, serializer);
    }
}

impl SseEncode for crate::RecoveryActionKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::RecoveryActionKindDto::RetryStartup => 0,
                crate::RecoveryActionKindDto::ResetAppearanceSettings => 1,
                crate::RecoveryActionKindDto::ExportDiagnostics => 2,
                crate::RecoveryActionKindDto::CopyTechnicalDetails => 3,
                crate::RecoveryActionKindDto::OpenDataDirectory => 4,
                crate::RecoveryActionKindDto::Exit => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::RuntimeEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.runtime_instance_id, serializer);
        <u64>::sse_encode(self.sequence, serializer);
        <u64>::sse_encode(self.occurred_at_ms, serializer);
        <crate::RuntimeEventPayloadDto>::sse_encode(self.payload, serializer);
    }
}

impl SseEncode for crate::RuntimeEventPayloadDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::RuntimeEventPayloadDto::RuntimeStateChanged { lifecycle } => {
                <i32>::sse_encode(0, serializer);
                <crate::RuntimeLifecycleDto>::sse_encode(lifecycle, serializer);
            }
            crate::RuntimeEventPayloadDto::StartupFailed { phase } => {
                <i32>::sse_encode(1, serializer);
                <crate::StartupPhaseDto>::sse_encode(phase, serializer);
            }
            crate::RuntimeEventPayloadDto::AppearanceSettingsChanged => {
                <i32>::sse_encode(2, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::RuntimeLifecycleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::RuntimeLifecycleDto::Uninitialized => 0,
                crate::RuntimeLifecycleDto::Starting => 1,
                crate::RuntimeLifecycleDto::Ready => 2,
                crate::RuntimeLifecycleDto::StartupFailed => 3,
                crate::RuntimeLifecycleDto::ShuttingDown => 4,
                crate::RuntimeLifecycleDto::Stopped => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::RuntimeStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.runtime_instance_id, serializer);
        <crate::RuntimeLifecycleDto>::sse_encode(self.lifecycle_state, serializer);
        <Option<crate::StartupPhaseDto>>::sse_encode(self.startup_phase, serializer);
        <Option<crate::StartupFailureDto>>::sse_encode(self.startup_failure, serializer);
    }
}

impl SseEncode for crate::SafeContextEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.field, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::StartupFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::StartupPhaseDto>::sse_encode(self.phase, serializer);
        <crate::ApplicationErrorDto>::sse_encode(self.error, serializer);
        <Vec<crate::RecoveryActionDto>>::sse_encode(self.recovery_actions, serializer);
    }
}

impl SseEncode for crate::StartupPhaseDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::StartupPhaseDto::EnvironmentInitialization => 0,
                crate::StartupPhaseDto::ObservabilityInitialization => 1,
                crate::StartupPhaseDto::ConfigurationInitialization => 2,
                crate::StartupPhaseDto::PersistenceInitialization => 3,
                crate::StartupPhaseDto::SettingsInitialization => 4,
                crate::StartupPhaseDto::CoreServicesInitialization => 5,
                crate::StartupPhaseDto::EventInfrastructureInitialization => 6,
                crate::StartupPhaseDto::ReadinessValidation => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::TechnicalDetailsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.text, serializer);
    }
}

impl SseEncode for crate::ThemeModeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::ThemeModeDto::System => 0,
                crate::ThemeModeDto::Light => 1,
                crate::ThemeModeDto::Dark => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::UpdateAppearanceSettingsRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::ThemeModeDto>::sse_encode(self.theme_mode, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    #[allow(unsafe_code)]

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
