[package]
name = "argus-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
test-support = []

[lints]
workspace = true

[dependencies]
argus-application = { path = "../argus-application" }
argus-domain = { path = "../argus-domain" }
rusqlite.workspace = true
sha2.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
