[package]
name = "argus-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
test-support = []

[lints]
workspace = true

[dependencies]
aes.workspace = true
argus-application = { path = "../argus-application" }
argus-domain = { path = "../argus-domain" }
blake3.workspace = true
chd.workspace = true
flate2.workspace = true
fs2.workspace = true
image.workspace = true
keyring.workspace = true
keyring-core.workspace = true
lzma-rust2.workspace = true
oxiarc-bzip2.workspace = true
oxiarc-core.workspace = true
oxiarc-lzma.workspace = true
ruzstd.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
sevenz-rust2.workspace = true
ureq.workspace = true
zeroize.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
