[package]
name = "argus-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
argus-application = { path = "../argus-application" }
argus-runtime = { path = "../argus-runtime" }
flutter_rust_bridge.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
